import { NETWORK_NAMES } from '@constants/chain-info';
import { Network } from 'alchemy-sdk';
import { env } from 'next-runtime-env';

export const ALCHEMY_KEYS = {
  [NETWORK_NAMES.ETHEREUM]: env('NEXT_PUBLIC_ALCHEMY_ETHEREUM_API_KEY') || 'THLzcjj0X_ktVcj80LZ60_twjxdWuUso',
  [NETWORK_NAMES.GOERLI]: env('NEXT_PUBLIC_ALCHEMY_GOERLI_API_KEY') || 'XDkXOl3fIkG3-XFvRmaa313PPJEehNx4',
  [NETWORK_NAMES.SEPOLIA]: env('NEXT_PUBLIC_ALCHEMY_SEPOLIA_API_KEY') || 'lnkxjj_rKFZRHqrrIvoerSJtzIdt2ElK',
  [NETWORK_NAMES.POLYGON]: env('NEXT_PUBLIC_ALCHEMY_POLYGON_API_KEY') || 'gQ41RwtnmeUVJtVLRSKGE8_V-dTWV7WD',
  [NETWORK_NAMES.POLYGON_MUMBAI]: env('NEXT_PUBLIC_ALCHEMY_MUMBAI_API_KEY') || '9b1326CuGOhpxr_RhB2QoPXKpfbuJsDF',
  [NETWORK_NAMES.POLYGON_AMOY]: env('NEXT_PUBLIC_ALCHEMY_AMOY_API_KEY') || 'mGHV_FIuWA5FjoM_Rb5twsukDo2-TB79',
  [NETWORK_NAMES.OPTIMISM]: env('NEXT_PUBLIC_ALCHEMY_OPTIMISM_API_KEY') || 'NyNr8gCoYyusotfANwHTuRhIQp62ZF3u',
  [NETWORK_NAMES.OPTIMISM_GOERLI]:
    env('NEXT_PUBLIC_ALCHEMY_OPTIMISM_GOERLI_API_KEY') || 'ynnAby9IhcpGA9l3x3nqD5zuE4r2gWo4',
  [NETWORK_NAMES.ARBITRUM_ONE]: env('NEXT_PUBLIC_ALCHEMY_ARBITRUM_ONE_API_KEY') || '8rzA2E8pLknmZf2nFz68vmfO_5m3NBG1',
  [NETWORK_NAMES.ARBITRUM_SEPOLIA]:
    env('NEXT_PUBLIC_ALCHEMY_ARBITRUM_SEPOLIA_API_KEY') || 'jnVUAQ2a_UaYArLhGq5xTb4N_zkkZOwd',
  [NETWORK_NAMES.BASE]: env('NEXT_PUBLIC_ALCHEMY_BASE_API_KEY') || 'STC7h-bp4V-lW38b2W2aPYDR5uBOyOUG',
  [NETWORK_NAMES.BASE_SEPOLIA]: env('NEXT_PUBLIC_ALCHEMY_BASE_SEPOLIA_API_KEY') || 'L2HXc7dDnRk0OQw5XFHM8lGacT5rrUN2',
} as const;

export const ALCHEMY_NETWORKS = {
  [NETWORK_NAMES.ETHEREUM]: Network.ETH_MAINNET,
  [NETWORK_NAMES.GOERLI]: Network.ETH_GOERLI,
  [NETWORK_NAMES.SEPOLIA]: Network.ETH_SEPOLIA,
  [NETWORK_NAMES.POLYGON]: Network.MATIC_MAINNET,
  [NETWORK_NAMES.POLYGON_MUMBAI]: Network.MATIC_MUMBAI,
  [NETWORK_NAMES.POLYGON_AMOY]: Network.MATIC_AMOY,
  [NETWORK_NAMES.OPTIMISM]: Network.OPT_MAINNET,
  [NETWORK_NAMES.OPTIMISM_GOERLI]: Network.OPT_GOERLI,
  [NETWORK_NAMES.ARBITRUM_ONE]: Network.ARB_MAINNET,
  [NETWORK_NAMES.ARBITRUM_SEPOLIA]: Network.ARB_SEPOLIA,
  [NETWORK_NAMES.BASE]: Network.BASE_MAINNET,
  [NETWORK_NAMES.BASE_SEPOLIA]: Network.BASE_SEPOLIA,
} as const;
