declare module '@fortmatic/ledger-bridge-tezos' {}
declare module '@fortmatic/ledger-bridge-harmony' {}
declare module '@fortmatic/ledger-bridge-flow' {}
declare module '@fortmatic/ledger-bridge-icon' {}
declare module '@fortmatic/ledger-bridge-zilliqa' {}
declare module '@fortmatic/ledger-bridge-polkadot' {}
declare module '@fortmatic/ledger-bridge-solana' {}
declare module '@fortmatic/ledger-bridge-avalanche' {}
declare module '@fortmatic/ledger-bridge-algorand' {}
declare module '@fortmatic/ledger-bridge-cosmos' {}
declare module '@fortmatic/ledger-bridge-bitcoin' {}
declare module '@fortmatic/ledger-bridge-near' {}
declare module '@fortmatic/ledger-bridge-conflux' {}
declare module '@fortmatic/ledger-bridge-terra' {}
declare module '@fortmatic/ledger-bridge-taquito' {}
declare module '@fortmatic/ledger-bridge-ed' {}
declare module '@fortmatic/ledger-bridge-hedera' {}
declare module '@fortmatic/ledger-bridge-aptos' {}
declare module '@fortmatic/ledger-bridge-sui' {}
declare module '@fortmatic/ledger-bridge-kadena' {}
